topics:
  - title: "Iran Conflict 2026"
    query_keywords:
      - "Iran conflict official statement 2026"
        #      - "Iran war government response 2026"
        #      - "Iran crisis diplomatic position 2026"
    countries_of_interest:
      - "United States"
        #      - "Israel"
      - "Iran"
        #      - "Russia"
        #      - "China"
      - "Japan"
        #      - "United Kingdom"
        #      - "France"
      - "Germany"
        #      - "Saudi Arabia"
